import { IIndState } from '../module/indiastate';

export const stateIndia: Array<IIndState> = [
  { stateName: 'Andhra Pradesh', language: 'Telugu' },
  { stateName: 'Arunachal Pradesh', language: 'English' },
  { stateName: 'Assam', language: 'Assamese' },
  { stateName: 'Bihar', language: 'Hindi' },
  { stateName: 'Chhattisgarh', language: 'Hindi' },
  { stateName: 'Goa', language: 'Konkani' },
  { stateName: 'Gujarat', language: 'Gujarati' },
  { stateName: 'Haryana', language: 'Hindi' },
  { stateName: 'Himachal Pradesh', language: 'Hindi' },
  { stateName: 'Jharkhand', language: 'Hindi' },
  { stateName: 'Karnataka', language: 'Kannada' },
  { stateName: 'Kerala', language: 'Malayalam' },
  { stateName: 'Madhya Pradesh', language: 'Hindi' },
  { stateName: 'Maharashtra', language: 'Marathi' },
  { stateName: 'Manipur', language: 'Meitei (Manipuri)' },
  { stateName: 'Meghalaya', language: 'English' },
  { stateName: 'Mizoram', language: 'Mizo' },
  { stateName: 'Nagaland', language: 'English' },
  { stateName: 'Odisha', language: 'Odia' },
  { stateName: 'Punjab', language: 'Punjabi' },
  { stateName: 'Rajasthan', language: 'Hindi' },
  { stateName: 'Sikkim', language: 'English' },
  { stateName: 'Tamil Nadu', language: 'Tamil' },
  { stateName: 'Telangana', language: 'Telugu' },
  { stateName: 'Tripura', language: 'Bengali' },
  { stateName: 'Uttar Pradesh', language: 'Hindi' },
  { stateName: 'Uttarakhand', language: 'Hindi' },
  { stateName: 'West Bengal', language: 'Bengali' },
];
